name: Release
on:
  push:
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Create 2D Asset
      run: |
        zip -r Scenario2D.zip Scenario README.md "Scenario2DPackageInstaller.cs" Scenario2D.wlt "ScenarioPackageInstaller2.cs"
    - name: Create 3D Asset
      run: |
        zip -r Scenario3D.zip Scenario README.md "Scenario3DPackageInstaller.cs" Scenario3D.wlt "ScenarioPackageInstaller2.cs"
    - name: Upload 2D Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          Scenario2D.zip
          LICENSE
          README.md
    - name: Upload 3D Asset
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: |
          Scenario3D.zip
          LICENSE
          README.md
